import styles from "../styles/globals.css";
import { Navigation } from "./components/navigation";
import { Lato } from "next/font/google";
const lato = Lato({
  subsets: ["latin"],
  weight: ['100', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Spa</title>
      </head>
      <body className={lato.className}>
        <div className={styles.main}>
          {children}
          <Navigation />
          </div>  
      </body>
    </html>
  );
}
